//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersHistory
    {
        public long Id { get; set; }
        public string wagonControlNo { get; set; }
        public string trainNo { get; set; }
        public string areaName { get; set; }
        public string currentStationName { get; set; }
        public string entranceSolarDate { get; set; }
        public string entranceTime { get; set; }
        public Nullable<int> distance { get; set; }
        public string goodsType { get; set; }
        public string sourceStationName { get; set; }
        public string destinationStationName { get; set; }
        public string billOfLadingNo { get; set; }
        public string trainSourcestationName { get; set; }
        public string trainDestinationStationName { get; set; }
        public Nullable<System.DateTime> entranceDateTime { get; set; }
        public Nullable<System.DateTime> fetchTime { get; set; }
    }
}
