//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersHistoryFetchLog
    {
        public int Id { get; set; }
        public string wagonNo { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public Nullable<System.DateTime> fetchTimeStart { get; set; }
        public Nullable<System.DateTime> fetchTimeEnd { get; set; }
        public Nullable<int> state { get; set; }
    }
}
