//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class logisticEntities : DbContext
    {
        public logisticEntities()
            : base("name=logisticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<PWS0Agencies> PWS0Agencies { get; set; }
        public virtual DbSet<PWS0AgenciesGeos> PWS0AgenciesGeos { get; set; }
        public virtual DbSet<PWS0BillOfLadings> PWS0BillOfLadings { get; set; }
        public virtual DbSet<PWS0Goods> PWS0Goods { get; set; }
        public virtual DbSet<PWS0StateCities> PWS0StateCities { get; set; }
        public virtual DbSet<PWS0Stations> PWS0Stations { get; set; }
        public virtual DbSet<PWS0StationsGeos> PWS0StationsGeos { get; set; }
        public virtual DbSet<PWS0TrainsBarry> PWS0TrainsBarry { get; set; }
        public virtual DbSet<PWS0TrainsPassengers> PWS0TrainsPassengers { get; set; }
        public virtual DbSet<raiBillOfLadingsTracking> raiBillOfLadingsTrackings { get; set; }
        public virtual DbSet<raiTrainPassengersLastStatu> raiTrainPassengersLastStatus { get; set; }
        public virtual DbSet<raiWagon_Info_Tracking> raiWagon_Info_Tracking { get; set; }
        public virtual DbSet<rwmmsVehicleOwner> rwmmsVehicleOwners { get; set; }
        public virtual DbSet<rwmmsVehicleOwnersDetail> rwmmsVehicleOwnersDetails { get; set; }
        public virtual DbSet<rwmmsWagonPart> rwmmsWagonParts { get; set; }
        public virtual DbSet<rwmmsWagonPartsGroup> rwmmsWagonPartsGroups { get; set; }
        public virtual DbSet<Wagon> Wagons { get; set; }
        public virtual DbSet<WagonsType> WagonsTypes { get; set; }
    }
}
