//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWS0StationsGeos
    {
        public string type { get; set; }
        public string id { get; set; }
        public string geometryType { get; set; }
        public string geometryCoordinates { get; set; }
        public string geometry_name { get; set; }
        public int StationId { get; set; }
    }
}
