//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWS0Stations
    {
        public int Id { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> alt { get; set; }
        public string name { get; set; }
        public string name2 { get; set; }
        public Nullable<int> stcode { get; set; }
        public string bus { get; set; }
        public string metro { get; set; }
        public string taxi { get; set; }
        public string other { get; set; }
        public string cellOffice { get; set; }
        public string parkingtim { get; set; }
        public string sakohamlkh { get; set; }
        public string daftarforo { get; set; }
        public string kioskkhari { get; set; }
        public string khodpardaz { get; set; }
        public string telephonom { get; set; }
        public string internetbi { get; set; }
        public string balabar { get; set; }
        public string ramp { get; set; }
        public string postbehdas { get; set; }
        public string ambolans { get; set; }
        public string vilcher { get; set; }
        public string masirnabin { get; set; }
        public string amanatketa { get; set; }
        public string tanaqolat { get; set; }
        public string soqat { get; set; }
        public string mobile { get; set; }
        public string sanayedast { get; set; }
        public string reservhote { get; set; }
        public string irani { get; set; }
        public string farangi { get; set; }
        public string bajetahvil { get; set; }
        public string salonentez { get; set; }
        public string salontashr { get; set; }
        public string namazkhone { get; set; }
        public string restoran { get; set; }
        public string vahedetela { get; set; }
        public string ashia { get; set; }
        public string sandoq { get; set; }
        public string saatkaranb { get; set; }
        public string saatkarbaj { get; set; }
        public string agency { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<int> cityid { get; set; }
        public string cityname { get; set; }
        public string statename { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> TaghlilStationID { get; set; }
        public Nullable<int> taghlilid { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
        public string alternateNames { get; set; }
    }
}
