//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rwmmsVehicleOwnersDetail
    {
        public int Id { get; set; }
        public string wFName { get; set; }
        public string wLName { get; set; }
        public string wFatherName { get; set; }
        public string wCertNo { get; set; }
        public string wRegisterCity { get; set; }
        public string wMeliNo { get; set; }
        public string wPostalCode { get; set; }
        public string wEmail { get; set; }
        public string wMobileNumber { get; set; }
        public string wBirthDate { get; set; }
        public string wAddress { get; set; }
        public Nullable<int> vehicleOwnerId { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public string Source { get; set; }
    }
}
