//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rwmmsWagonPart
    {
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string wPartName { get; set; }
        public string wPartNameLatin { get; set; }
        public Nullable<int> wCountInGroup { get; set; }
        public Nullable<int> wCountInWagon { get; set; }
        public Nullable<decimal> wWeight { get; set; }
        public string wMapNumber { get; set; }
        public string wMapPicPath { get; set; }
        public string wMapPic1Path { get; set; }
        public string wMapPic2Path { get; set; }
        public string wMapPic3Path { get; set; }
        public string wMapPic4Path { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
    }
}
