//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWS0Goods
    {
        public int Id { get; set; }
        public string goodsName { get; set; }
        public string AlternateNames { get; set; }
    }
}
