//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWS0TrainsPassengers
    {
        public int Id { get; set; }
        public Nullable<int> jTrain_No { get; set; }
        public Nullable<int> jCurrent_Station_Code { get; set; }
        public string jEntrance_Date { get; set; }
        public string jEntrance_Time { get; set; }
        public string jExit_Date { get; set; }
        public string jExit_Time { get; set; }
        public string jDeparture_Date { get; set; }
        public string jDeparture_Time { get; set; }
        public Nullable<int> jSource_Station_Code { get; set; }
        public Nullable<int> jDestination_Station_Code { get; set; }
        public string jDestination_Program_Time_In { get; set; }
        public string jCurrent_Program_Time_In { get; set; }
        public string jDeparture_Program_Time_Out { get; set; }
        public Nullable<System.DateTime> jUpdate_DateTime { get; set; }
        public Nullable<int> jDelayMinute { get; set; }
        public Nullable<int> jArivalHours { get; set; }
        public Nullable<int> CurrentStationId { get; set; }
        public Nullable<System.DateTime> EntranceDateTime { get; set; }
        public Nullable<System.DateTime> ExitDateTime { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<int> SourceStationId { get; set; }
        public Nullable<int> DestinationStationId { get; set; }
        public Nullable<System.TimeSpan> DestinationProgramTimeIn { get; set; }
        public Nullable<System.TimeSpan> CurrentProgramTimeIn { get; set; }
        public Nullable<System.TimeSpan> DepartureProgramTimeOut { get; set; }
        public string SourceURL { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
        public Nullable<int> CycleNumber { get; set; }
    }
}
