//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWS0Agencies
    {
        public int Id { get; set; }
        public string AgencyCode { get; set; }
        public string AgencyName { get; set; }
        public string AgencyStreet { get; set; }
        public string AgencyTel { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string ProvinceCode { get; set; }
        public string cityCode { get; set; }
        public string cityName { get; set; }
        public string provinceName { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
    }
}
