//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class raiWagon_Info_Tracking
    {
        public int Id { get; set; }
        public Nullable<int> wRowNo { get; set; }
        public Nullable<long> wWagonNo { get; set; }
        public Nullable<int> wTrainNo { get; set; }
        public string wAreaName { get; set; }
        public string wCurrentStationName { get; set; }
        public string wEnteranceDate { get; set; }
        public string wEnteranceTime { get; set; }
        public string wExitDate { get; set; }
        public string wExitTime { get; set; }
        public string wSourceStationName { get; set; }
        public string wDestinationStationName { get; set; }
        public Nullable<int> wDistance { get; set; }
        public string wBarType { get; set; }
        public Nullable<long> wBillOfLadingNo { get; set; }
        public string wTrainSourceStationName { get; set; }
        public string wTrainDestinationStationName { get; set; }
        public Nullable<int> wagonId { get; set; }
        public Nullable<int> trainId { get; set; }
        public Nullable<int> currentStationId { get; set; }
        public Nullable<System.DateTime> enteranceDateTime { get; set; }
        public Nullable<System.DateTime> exitDateTime { get; set; }
        public Nullable<int> sourceStationId { get; set; }
        public Nullable<int> destinationStationId { get; set; }
        public Nullable<int> goodsID { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public string Source { get; set; }
    }
}
