//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rwmmsVehicleOwner
    {
        public int Id { get; set; }
        public string wCompanyName { get; set; }
        public string wCompanyId { get; set; }
        public string wRegisterNo { get; set; }
        public string wRegisterCityName { get; set; }
        public string wRegsiterPersianDate { get; set; }
        public string wIntroductionFile { get; set; }
        public string companyName { get; set; }
        public string ShenaseMeli { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public string AlternateNames { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> FetchTime { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public string Source { get; set; }
    }
}
