//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailSiteDataGrabber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        public int Id { get; set; }
        public Nullable<long> wagonNo { get; set; }
        public Nullable<int> wagonTypeId { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> capacity { get; set; }
        public string wagonControlNo { get; set; }
        public string wrWagonTypeName { get; set; }
        public string wrBrakeType { get; set; }
        public string wrChassisSerial { get; set; }
        public string wrRivNo { get; set; }
        public string wrCountry { get; set; }
        public string wrBoogieType { get; set; }
        public string wrCompanyManufacturer { get; set; }
        public Nullable<double> wrCapacity { get; set; }
        public Nullable<int> wrProductionYear { get; set; }
        public Nullable<int> wrAxisCount { get; set; }
        public string wrHookType { get; set; }
        public Nullable<double> wrNetWeight { get; set; }
        public Nullable<int> wrControlDigit { get; set; }
        public Nullable<int> wrDaysRemainToRepair { get; set; }
        public string wrOwnerName { get; set; }
        public string wrOwnershipType { get; set; }
    }
}
